# Move to Pose using moveit

### Request Params:
# The pose to move to
Pose goal_pose
---
### Result Params:
#### The final result of the planning and execution
Pose final_pose
moveit_msgs/MotionPlanResponse plan_response
moveit_msgs/MotionSequenceResponse motion_response

---
### Feedback Params:
#### The current width of the gripper at this timestep
Pose current_pose
moveit_msgs/MotionPlanResponse plan_response


