<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="$(arg name)">

    <xacro:property name="plate_depth" value="0.0127" />
    <xacro:property name="plate_size" value="0.30" />

    <xacro:arg name="name" default="ur" />
    <xacro:arg name="ur_type" default="ur5x" />
    <xacro:arg name="tf_prefix" default="" />
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/$(arg ur_type)/joint_limits.yaml"/>
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/$(arg ur_type)/default_kinematics.yaml"/>
    <xacro:arg name="physical_params" default="$(find ur_description)/config/$(arg ur_type)/physical_parameters.yaml"/>
    <xacro:arg name="visual_params" default="$(find ur_description)/config/$(arg ur_type)/visual_parameters.yaml"/>

    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro" />
    <xacro:include filename="onrobot_quick_changer.urdf" />
    <xacro:include filename="onrobot_eyes.urdf" />
    <xacro:include filename="$(find realsense2_description)/urdf/_d415.urdf.xacro" />


    <xacro:ur_robot
        name="$(arg name)"
        tf_prefix="$(arg tf_prefix)"
        joint_limits_parameter_file="$(arg joint_limit_params)"
        kinematics_parameter_file="$(arg kinematics_params)"
        physical_parameter_file="$(arg physical_params)"
        visual_parameter_file="$(arg visual_params)"
        parent="mount_plate_attach_link"
    >
        <origin xyz="0 0 0"/>
    </xacro:ur_robot>
    <xacro:sensor_d415 parent="onrobot_eyes_base_link" use_nominal_extrinsics="true"
        add_plug="false" use_mesh="false">
        <!-- 
            These measurements are not 100% accurate, they're the best
            I could get based on manually aligning it in blender.
            We need to preform camera extrinsics calibration manually to get these values.
            industrial_calibration seems like a good package for doing this.
        -->
        <origin xyz="-0.01091 0.105055 0.019792" rpy="-${pi/2} -${pi/2} 0" />
    </xacro:sensor_d415>

    <!-- This is the camera link provided by Sam, not sure how it was obtained -->
    <link name="camera_sam_link" />
    <joint name="camera_sam_link_joint" type="fixed">
        <origin rpy="0 -${pi/2} ${pi/2}" xyz="-0.018 -0.11 0.031" />
        <parent link="wrist_3_link" />
        <child link="camera_sam_link" />
        <axis xyz="0 0 0" />
    </joint>

    <link name="mount_plate_attach_link"/>
    <link name="mount_plate_base_link">
        <visual>
            <origin xyz="0 0 ${plate_depth/2}" />
            <geometry>
                <box size="${plate_size} ${plate_size} ${plate_depth}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${plate_depth/2}" />
            <geometry>
                <box size="${plate_size} ${plate_size} ${plate_depth}" />
            </geometry>
        </collision>
    </link>


    <joint name="mount_joint" type="fixed">
        <origin xyz="0 0 ${plate_depth}" />
        <parent link="mount_plate_base_link" />
        <child link="mount_plate_attach_link" />
        <axis xyz="0 0 0" />
    </joint>

    <joint name="eyes_joint" type="fixed">
        <origin rpy="0 0 ${pi}" xyz="0 0 0" />
        <parent link="tool0" />
        <child link="onrobot_eyes_base_link" />
        <axis xyz="0 0 0" />
    </joint>
    <joint name="quick_changer_joint" type="fixed">
        <origin rpy="0 0 ${pi/2}" xyz="0 0 0" />
        <parent link="onrobot_eyes_tool_link" />
        <child link="onrobot_quick_changer_base_link" />
        <axis xyz="0 0 0" />
    </joint>

</robot>