<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur5e">

    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro" />
    <xacro:include filename="$(find par_pkg)/urdf/onrobot_eyes.xacro" />
    <xacro:include filename="$(find par_pkg)/urdf/onrobot_quick_changer.xacro" />
    <xacro:include filename="$(find par_pkg)/urdf/onrobot_rg2.xacro" />


    <xacro:property name="mount_plate_size" value="0.194" />
    <xacro:property name="mount_plate_depth" value="0.0127" />

    <xacro:macro
        name="ur_assembly"
        params="
        low_poly:='true'
        gripper:='true'
        mounting_angle:=0
        camera_angle:=0
        name
        ur_type
    tf_prefix
    parent
    joint_limits_parameters_file
    kinematics_parameters_file
    physical_parameters_file
    visual_parameters_file
    generate_ros2_control_tag:=true
    transmission_hw_interface:=hardware_interface/PositionJointInterface
    safety_limits:=false
    safety_pos_margin:=0.15
    safety_k_position:=20
    use_fake_hardware:=false
    fake_sensor_commands:=false
    sim_gazebo:=false
    sim_ignition:=false
    headless_mode:=false
    initial_positions:=${dict(shoulder_pan_joint=0.0,shoulder_lift_joint=-1.57,elbow_joint=0.0,wrist_1_joint=-1.57,wrist_2_joint=0.0,wrist_3_joint=0.0)}
    use_tool_communication:=false
    tool_voltage:=0
    tool_parity:=0
    tool_baud_rate:=115200
    tool_stop_bits:=1
    tool_rx_idle_chars:=1.5
    tool_tx_idle_chars:=3.5
    tool_device_name:=/tmp/ttyUR
    tool_tcp_port:=54321
    robot_ip:=0.0.0.0
    script_filename:=to_be_filled_by_ur_robot_driver
    output_recipe_filename:=to_be_filled_by_ur_robot_driver
    input_recipe_filename:=to_be_filled_by_ur_robot_driver
    reverse_port:=50001
    script_sender_port:=50002
    reverse_ip:=0.0.0.0
    script_command_port:=50004
    trajectory_port:=50003
    non_blocking_read:=true
    keep_alive_count:=2"
    >

        <link name="
    mount_plate_link">
            <visual>
                <origin xyz="
    0 0 -${mount_plate_depth/ 2}" />
                <geometry>
                    <mesh filename=" package:// par_pkg/ meshes/ visual/ base_plate.dae" />
                </geometry>
            </visual>
            <collision>
                <origin xyz=" 0 0 -${mount_plate_depth/ 2}" />
                <geometry>
                    <box size=" ${mount_plate_size} ${mount_plate_size} ${mount_plate_depth}" />
                </geometry>
            </collision>
        </link>


        <xacro:ur_robot
            name="${ur_type}"
            parent="mount_plate_link"
            tf_prefix="${tf_prefix}"
            joint_limits_parameters_file="${joint_limits_parameters_file}"
            kinematics_parameters_file="${kinematics_parameters_file}"
            physical_parameters_file="${physical_parameters_file}"
            visual_parameters_file="${visual_parameters_file}"
            transmission_hw_interface="${transmission_hw_interface}"
            safety_limits="${safety_limits}"
            safety_pos_margin="${safety_pos_margin}"
            safety_k_position="${safety_k_position}"
            use_fake_hardware="${use_fake_hardware}"
            fake_sensor_commands="${fake_sensor_commands}"
            sim_gazebo="${sim_gazebo}"
            sim_ignition="${sim_ignition}"
            headless_mode="${headless_mode}"
            initial_positions="${xacro.load_yaml(initial_positions_file)}"
            use_tool_communication="${use_tool_communication}"
            tool_voltage="${tool_voltage}"
            tool_parity="${tool_parity}"
            tool_baud_rate="${tool_baud_rate}"
            tool_stop_bits="${tool_stop_bits}"
            tool_rx_idle_chars="${tool_rx_idle_chars}"
            tool_tx_idle_chars="${tool_tx_idle_chars}"
            tool_device_name="${tool_device_name}"
            tool_tcp_port="${tool_tcp_port}"
            robot_ip="${robot_ip}"
            script_filename="${script_filename}"
            output_recipe_filename="${output_recipe_filename}"
            input_recipe_filename="${input_recipe_filename}"
            reverse_ip="${reverse_ip}"
            script_command_port="${script_command_port}"
            reverse_port="${reverse_port}"
            script_sender_port="${script_sender_port}"
            trajectory_port="${trajectory_port}"
        >
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:ur_robot>

        <xacro:onrobot_eyes
            parent="tool0"
            low_poly="${low_poly}"
            camera_angle="${camera_angle}"
        />

        <xacro:onrobot_quick_changer
            parent="onrobot_eyes_tool_link"
            low_poly="${low_poly}"
        />

        <xacro:if value="${gripper}">
            <xacro:onrobot_rg2_gripper parent="onrobot_quick_changer_tool_link"
                low_poly="${low_poly}" />
        </xacro:if>


        <joint name="mount_plate_joint" type="fixed">
            <origin xyz="0 0 ${mount_plate_depth}" rpy="0 0 ${mounting_angle}" />
            <parent link="world" />
            <child link="mount_plate_link" />
        </joint>


    </xacro:macro>


</robot>